package com.kslides

import com.kslides.CssValue.Companion.writeCssToHead
import com.kslides.CssValue.Companion.writeStyleToHead
import com.kslides.InternalUtils.resolveAgainst
import com.pambrose.common.util.ensureSuffix
import io.ktor.http.ContentType
import io.ktor.http.fromFilePath
import kotlinx.html.BODY
import kotlinx.html.HTML
import kotlinx.html.a
import kotlinx.html.body
import kotlinx.html.div
import kotlinx.html.dom.append
import kotlinx.html.dom.document
import kotlinx.html.dom.serialize
import kotlinx.html.head
import kotlinx.html.html
import kotlinx.html.id
import kotlinx.html.img
import kotlinx.html.link
import kotlinx.html.meta
import kotlinx.html.script
import kotlinx.html.style
import kotlinx.html.title
import org.w3c.dom.Document
import java.io.FileNotFoundException

internal object Page {
  private val preRegex = Regex("\\s*<pre.*>\\s*")
  private val codeRegex = Regex("\\s*<code.*>\\s*")

  /**
   * What one page render needs: the deck, the output mode, and the two prefixes that follow from
   * where the page will sit.
   *
   * Private because `Page`'s builders are its only consumers. The rule they apply,
   * [InternalUtils.resolveAgainst], lives there so consumers that cannot reach here share it.
   *
   * @param rootPrefix the walk from this page back to the output root — `"/"` under HTTP, `"../"`
   *   per directory level for a filesystem deck, empty at the root.
   */
  private class RenderContext(
    val p: Presentation,
    val useHttp: Boolean,
    val rootPrefix: String,
  ) {
    val config = p.finalConfig

    // reveal.js assets are served from the classpath under a fixed directory in HTTP mode, and
    // copied to the configurable staticRootDir on disk.
    private val assetDir = if (useHttp) KSlides.REVEAL_ROOT_DIR else p.kslides.outputConfig.staticRootDir

    /** Where the reveal.js assets sit, relative to this page. */
    val srcPrefix = "$rootPrefix$assetDir".ensureSuffix("/")

    /**
     * The prefix a relative path with this origin resolves against, for this render. Exhaustive by
     * design: this is the one site a new [AssetOrigin] has to be taught about, so adding one should
     * fail to compile here rather than silently resolve against the assets.
     */
    fun AssetOrigin.prefix(): String =
      when (this) {
        AssetOrigin.REVEAL_ASSETS -> srcPrefix
        AssetOrigin.OUTPUT_ROOT -> rootPrefix
      }
  }

  /**
   * @param rootPrefix see [RenderContext]. Everything root-relative the page emits is built from
   *   it: reveal.js asset links, the favicon, and author-supplied corner/logo images here;
   *   iframe/image srcs via [Presentation.renderRootPrefix].
   */
  internal fun generatePage(
    p: Presentation,
    useHttp: Boolean = true,
    rootPrefix: String = "/",
  ): String =
  // Serialize concurrent Ktor renders on renderLock: rendering mutates shared per-render state
  // (p.kslides.slideCount, reconstructed verticalSlides{} child lists, per-slide iframe counters).
    // See KSlides.renderLock.
    synchronized(p.kslides.renderLock) {
      p.kslides.slideCount = 0
      p.codeStyleClasses.clear()
      p.mermaidUsed = false

      val ctx = RenderContext(p, useHttp, rootPrefix)
      // Publish the same walk to slide content, which has no parameter channel to receive it.
      p.renderRootPrefix = ctx.rootPrefix
      val htmldoc =
        document {
          append.html {
            ctx.generateHead(this)
            ctx.generateBody(this)
          }
        }

      // Protect characters inside markdown blocks that get escaped by HTMLStreamBuilder
      val nodeList = htmldoc.getElementsByTagName("*")
      for (i in 0..<nodeList.length) {
        val node = nodeList.item(i)
        if (node.nodeName == "section") {
          node.attributes.getNamedItem("data-separator")?.apply {
            nodeValue = nodeValue.replace("\n", "\\n")
            nodeValue = nodeValue.replace("\r", "\\r")
          }

          node.attributes.getNamedItem("data-separator-vertical")?.apply {
            nodeValue = nodeValue.replace("\n", "\\n")
            nodeValue = nodeValue.replace("\r", "\\r")
          }
        }
      }

      // Per-slide slideConfig{} blocks only run during body rendering — after generateHead has
      // already been built — so the code-style rules they produce have to be patched into the
      // head via the DOM rather than emitted by the head builder.
      if (p.codeStyleClasses.isNotEmpty()) {
        val rules =
          buildString {
            p.codeStyleClasses.forEach { (values, cssClass) ->
              val (codeFontSize, codeWrap) = values
              if (codeFontSize.isNotBlank())
                appendLine(".reveal .$cssClass pre { font-size: $codeFontSize; }")
              if (codeWrap)
                appendLine(".reveal .$cssClass pre code { white-space: pre-wrap; word-break: break-word; }")
            }
            // The wrap rule inherits into the line-number gutter generated by the highlight
            // plugin, where break-word lets the table squeeze two-digit numbers onto one digit
            // per line. Pin the gutter cells, mirroring reveal.js's own print-CSS pairing of
            // .hljs pre-wrap with .hljs-ln-numbers nowrap.
            if (p.codeStyleClasses.keys.any { it.second })
              appendLine(".reveal pre code .hljs-ln-numbers { white-space: nowrap; word-break: normal; }")
          }
        htmldoc.appendHeadStyle(rules)
      }

      // Like the code-style rules above, mermaid usage is only discovered while the body
      // renders, so its CSS is patched into the already-built head the same way.
      if (p.mermaidUsed)
        htmldoc.appendHeadStyle(Mermaid.headCss)

      // Badge styling goes through the head like every other feature CSS, so deck authors can
      // restyle or hide it with ordinary css{} rules (the client script only sets text/cursor).
      if (useHttp && p.kslides.outputConfig.followAlong)
        htmldoc.appendHeadStyle(FollowAlong.badgeCss)

      mergePreAndCode(htmldoc.serialize())
    }

  // Appends a <style> node to the already-built <head> for rules discovered during body
  // rendering.
  private fun Document.appendHeadStyle(rules: String) {
    // The document is always html > (head, body); scan the two children rather than the tree.
    val children = documentElement.childNodes
    val headNode = (0..<children.length).map(children::item).first { it.nodeName == "head" }
    val styleNode =
      createElement("style").apply {
        setAttribute("type", "text/css")
        // No media="screen" scoping: code-size and mermaid rules must also apply when printing.
        // Same layout convention as CssValue.writeCssToHead: \t\t\t-indented body, \t\t trailer.
        textContent = "\n${rules.trimEnd().prependIndent("\t\t\t")}\n\t\t"
      }
    headNode.appendChild(styleNode)
  }

  /**
   * Fix a copycode issue: reveal.js needs the `<pre>` and `<code>` tags on the same line. The
   * serializer emits them split across lines:
   * ```
   * <pre>
   *    <code>
   *    </code>
   * </pre>
   * ```
   * so when a `<code>` line immediately follows a `<pre>` line, pull it up onto the `<pre>` line.
   * `preFound` only bridges those two adjacent lines — it is reset on any other line so a later,
   * unrelated `<code>` is never merged (which would strip its leading whitespace).
   */
  internal fun mergePreAndCode(serialized: String): String =
    buildString {
      var preFound = false
      serialized
        .lines()
        .forEach { line ->
          when {
            line.matches(preRegex) -> {
              preFound = true
              append(line)
            }

            preFound && line.matches(codeRegex) -> {
              preFound = false
              append("${line.trimStart()}\n")
            }

            else -> {
              preFound = false
              append("$line\n")
            }
          }
        }
    }

  @Suppress("LongMethod")
  private fun RenderContext.generateHead(html: HTML) =
    html.head {
      meta {
        charset = "utf-8"
      }
      meta {
        name = "apple-mobile-web-app-capable"
        content = "yes"
      }
      meta {
        name = "apple-mobile-web-app-status-bar-style"
        content = "black-translucent"
      }
      meta {
        name = "viewport"
        content = "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
      }

      if (config.title.isNotBlank())
        title { +config.title }

      if (config.gaPropertyId.isNotBlank()) {
        rawHtml("\n")
        script {
          async = true
          src = "https://www.googletagmanager.com/gtag/js?id=${config.gaPropertyId}"
        }
        rawHtml("\n\n\t\t")
        script {
          rawHtml("\n")
          rawHtml(
            """
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());
                gtag('config', '${config.gaPropertyId}');
            """.trimIndent().prependIndent("\t\t\t"),
          )
          rawHtml("\n\t\t")
        }
      }

      rawHtml("\n")
      p.cssFiles.forEach {
        link(rel = "stylesheet") {
          href = it.filename.resolveAgainst(it.origin.prefix())
          if (it.id.isNotBlank())
            id = it.id
        }
      }

      // customTheme{} overrides, layered directly after the stylesheet links so they win over the
      // base theme while slides.css and css{} rules (emitted below) can still override them.
      writeStyleToHead(p.indentedCustomThemeCss, styleId = "custom-theme")

      // See PresentationConfig.favicon. The type attribute is a hint, so it is stated only when the
      // filename gives it away — a data: URI or an extension-less path gets none, and the browser
      // infers from the response instead.
      val favicon = config.favicon
      if (favicon.isNotBlank()) {
        rawHtml("\n")
        val faviconHref = favicon.resolveAgainst(rootPrefix)
        val faviconType = ContentType.fromFilePath(favicon).firstOrNull()?.toString()
        listOf("shortcut icon", "icon").forEach { iconRel ->
          link(rel = iconRel) {
            href = faviconHref
            if (faviconType != null)
              type = faviconType
          }
        }
      }

      rawHtml("\n")
      // No media="screen" scoping: author styles must also apply when printing (?print-pdf /
      // kslides-export), where screen-only styles would silently vanish from the PDF.
      style {
        rawHtml("\n")
        rawHtml(
          Page::class.java.classLoader
            .getResource("slides.css")
            ?.readText()
            ?.lines()
            ?.joinToString("\n") { "\t\t$it" }
            ?.prependIndent("\t")
            ?: throw FileNotFoundException("File not found: src/main/resources/slides.css"),
        )
        rawHtml("\n\t\t")
      }

      writeCssToHead(p.css)
    }

  @Suppress("CyclomaticComplexMethod", "LongMethod")
  private fun RenderContext.generateBody(html: HTML) =
    html.body {
      div("reveal") {
        if (config.topLeftHref.isNotBlank()) {
          a(href = config.topLeftHref, target = config.topLeftTarget.htmlVal, classes = "top-left") {
            if (config.topLeftTitle.isNotBlank())
              title = config.topLeftTitle
            if (config.topLeftSvg.isNotBlank())
              rawHtml(config.topLeftSvg)
            if (config.topLeftSvgSrc.isNotBlank())
              img(classes = config.topLeftSvgClass) {
                src = config.topLeftSvgSrc.resolveAgainst(rootPrefix)
                if (config.topLeftSvgStyle.isNotBlank())
                  style = config.topLeftSvgStyle
              }
            if (config.topLeftText.isNotBlank())
              +config.topLeftText
          }
        }

        if (config.topRightHref.isNotBlank()) {
          rawHtml("\n\t\t\t")
          a(href = config.topRightHref, target = config.topRightTarget.htmlVal, classes = "top-right") {
            if (config.topRightTitle.isNotBlank())
              title = config.topRightTitle
            if (config.topRightSvg.isNotBlank())
              rawHtml(config.topRightSvg)
            if (config.topRightSvgSrc.isNotBlank())
              img(classes = config.topRightSvgClass) {
                src = config.topRightSvgSrc.resolveAgainst(rootPrefix)
                if (config.topRightSvgStyle.isNotBlank())
                  style = config.topRightSvgStyle
              }
            if (config.topRightText.isNotBlank())
              +config.topRightText
          }
        }

        config.customThemeConfig.logoValue?.let { logo ->
          rawHtml("\n\t\t\t")
          // The image is ours to resolve; the link target, like the corner hrefs, is not.
          val logoSrc = logo.src.resolveAgainst(rootPrefix)
          if (logo.href.isBlank())
            img(classes = "kslides-logo") { src = logoSrc }
          else
            a(href = logo.href, classes = "kslides-logo") {
              img { src = logoSrc }
            }
        }

        rawHtml("\n")
        div("slides") {
          p.slides.forEach { slide -> slide.content(this, slide, useHttp) }
        }
      }

      rawHtml("\n\t\n")
      p.jsFiles.forEach { jsFile ->
        rawHtml("\t")
        script { src = jsFile.filename.resolveAgainst(jsFile.origin.prefix()) }
        rawHtml("\n")
      }

      rawHtml("\n\t")
      script {
        rawHtml("\n\t\tReveal.initialize({\n${p.toJs(config)}\t\t});\n\n")
      }

      // Only decks that actually contain a mermaid{} block pay for the Mermaid runtime. The flag
      // is set while the slides render above, which happens before this point in the body builder.
      if (p.mermaidUsed) {
        rawHtml("\n\t")
        script { src = Mermaid.MERMAID_JS_PATH.resolveAgainst(srcPrefix) }
        rawHtml("\n\t")
        script {
          rawHtml("\n${Mermaid.initScript(config.effectiveTheme).prependIndent("\t\t")}\n\t")
        }
        rawHtml("\n")
      }

      // Shared injection point for HTTP-only client scripts (live reload, follow-along). Never
      // emitted for filesystem output; each script is gated by its own output{} flag.
      injectClientScripts(p, useHttp)
    }

  /** Emits the HTTP-only client scripts whose output{} flags are enabled. */
  private fun BODY.injectClientScripts(
    p: Presentation,
    useHttp: Boolean,
  ) {
    if (!useHttp)
      return

    // Pre-indented once per JVM: this runs per HTTP request under the render lock.
    fun emit(indentedClientScript: String) {
      rawHtml("\n\t")
      script { rawHtml("\n$indentedClientScript\n\t") }
      rawHtml("\n")
    }

    val outputConfig = p.kslides.outputConfig
    if (outputConfig.devMode) emit(LiveReload.indentedClientScript)
    if (outputConfig.followAlong) emit(FollowAlong.indentedClientScript)
  }
}
